myblog/book/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
# from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import resolve_url
from django.urls import path, include
from .models import Book, Other
import datetime

from django.views.decorators.cache import cache_page



app_name='book'

class PostSitemap_Book(Sitemap):
    changefreq = "never"
    priority = 0.6

    def items(self):
        return Book.objects.filter(fin=True)

    def location(self, obj):
        data_info=(obj.post_day).strftime("%Y-%m-%d")
        # data_info= obj.post_day
        return resolve_url('book:book_info', data_info=data_info)+"1/"

    def lastmod(self, obj):
        return obj.post_day

class PostSitemap_Other(Sitemap):
    changefreq = "never"
    priority = 0.4

    def items(self):
        return Other.objects.all()

    def location(self, obj):
        data_info=(obj.post_day).strftime("%Y-%m-%d")
        # data_info= obj.post_day
        return resolve_url('book:others_info', data_info=data_info)

    def lastmod(self, obj):
        return obj.post_day

class StaticSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        name_list = ['profile', 'book-ic', 'others', 'privacy_policy', 'contact', 'book', 'top', 'sitemap_book-ic', 'ads']
        items = []
        for name_ in name_list:
            items.append("book:{}".format(name_))          
        return items

    def location(self, obj):
        return resolve_url(obj)


sitemaps = {
    'posts_book': PostSitemap_Book,
    'posts_other':PostSitemap_Other,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.TopView.as_view(), name="top"),
    path('quasar/', views.TopquasarView.as_view(), name="top_quasar"),

    path('categorys/', views.CategoryView.as_view(), name='category'),# 本のカテゴリー
    path('categorys/<slug:data_info>/', views.CategoryView.as_view(), name='category_infprofile', ),

    path('authors/', views.AuthorView.as_view(), name='author'), # 著者について全般
    path('authors/<data_info>/', views.AuthorView.as_view(), name='author_info'),

    path('publishers/', views.PublisherView.as_view(), name='publisher'), # 出版社情報
    path('publishers/<slug:data_info>/', views.PublisherView.as_view(), name='publisher_info'),

    path('series/', views.SeriesView.as_view(), name='series'), # シリーズもの本
    path('series/<slug:data_info>/', views.SeriesView.as_view(), name='series_info'), 

    path('books/', views.BookView.as_view(), name='book'), # 主に本の検索と
    path('books/<slug:data_info>/', views.BookrView.as_view(), name='book_info'), 
    path('books/<slug:data_info>/<int:data_info_page>/', views.BookView.as_view(), name='book_info_content'), 

    path('search', views.SearchView.as_view(), name='search' ), # 本の検索全般

    path('articles/', views.ArticlesView.as_view(), name='article'), # トピックスに近いもの

    # path('otherss/', views.OtherView.as_view(),  name='other'),
    path('others/shedule', views.Schedule.as_view(),  name='schedule'),

    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('book-ic/', views.Book_icView.as_view(), name="book-ic"),

    path('others/', views.OthersView.as_view(), name="others"),
    path('others/<slug:data_info>/', views.OthersView.as_view(), name="others_info"),


    path('privacypolicy', views.Privacy_policyView.as_view(), name="privacy_policy"),
    path('contact', views.ContactView.as_view(), name="contact"),
    

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},  name='sitemap'),
    path('sitemap/', views.SitemapView.as_view(),  name='sitemap_book-ic'),

    path('ads.txt/', views.ads, name='ads'),

    path('test/', views.test_,  name='test_'),
    
    # path('base', views.TestView.as_view(), name="base"),


    ]

if settings.DEBUG == True:
    urlpatterns.append(path('sns/books/<slug:data_info>/', views.Picture_snsView.as_view(),  name='picture_sns'))

# 


""" 予定-----------------------------
top
    -Recently （最近の投稿）
    -auther（著者）一覧のみ[（あいうえお順）/（男・女）/（年齢）]
        -著者の情報　＋　Book[カテゴリー/出版日]
    -Publisher（出版社）一覧のみ
        -出版社の情報　＋　Author[（あいうえお順）/（男・女）/（年齢）]
    -category（カテゴリー）
    -読む予定の本一覧a
    -外部リンク[アリクイちゃんねる/技術コンテンツ/ヨウヘイ]

search
    -カテゴリー
    -出版社
    -著者
    -日付

-----------------------------"""

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



# if settings.DEBUG != True:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('book.urls')),
#     ]
# else:
urlpatterns = [
    path('', include('book.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG == True:
    urlpatterns.append(path('admin/', admin.site.urls))

 



# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


# from django.views.static import serve  #追加

# url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  #追加

myblog/book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.aggregates import Count
from django.db.models.enums import Choices
from django.db.models.fields import SmallIntegerField, TimeField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.reverse_related import ManyToOneRel
from django.core.validators import MinLengthValidator, RegexValidator
import datetime


# いらないｰｰｰｰｰｰｰｰ
# sex_ = (
#     ("man", '男性'),
#     ("woman", '女性')
# )
# ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ

# Create your models here.


class Book(models.Model):
    isbn13 = models.CharField(max_length=14,
                                validators=[MinLengthValidator(14, '文字数が一致していません。例）978-4167174033'),
                                            RegexValidator(r'[0-9]{3}[-][0-9]{10}', '形式に当てはまっていません。例）978-4167174033')], null=True, blank=True)

    title = models.CharField('タイトル', max_length=100, null=True, blank=True)
    pages = models.SmallIntegerField('ページ数', null=True, blank=True)
    issue = models.DateField('発行日', null=True, blank=True) # [発行日, y m d]

    post_day = models.DateField('投稿日', null=True, blank=True) # [投稿日, y m d]
    update_day = models.DateField('更新日', null=True, blank=True) # [投稿日, y m d]


    YOUTH_CHOICES = (('Y', 'Youth'),('O', 'Old'))
    youth_choices = models.CharField('青春/白秋', choices=YOUTH_CHOICES, max_length=10)

    series_info = models.ForeignKey("Series", verbose_name=("シリーズ情報"), on_delete=models.CASCADE, null=True, blank=True)
    author_info = models.ForeignKey("Author", verbose_name=("著者情報"), on_delete=models.CASCADE, null=True, blank=True)
    # category_info = models.ManyToManyField("Category", verbose_name=("カテゴリー情報"), blank=True, related_name="category_info")
    category_info = models.ForeignKey("Category", verbose_name=("カテゴリー情報"), blank=True,null=True,on_delete=models.CASCADE)

    publisher_info = models.ForeignKey("Publisher", verbose_name=("出版社情報"), on_delete=models.CASCADE, null=True, blank=True)
    publisher_label_info = models.ForeignKey("Publisher_label", verbose_name=("レーベル"), on_delete=models.CASCADE, null=True, blank=True)

    contents = models.TextField("コンテンツ", null=True, blank=True)
    contents_synopsis =  models.TextField("あらすじ", null=True, blank=True)

    fin = models.BooleanField('完読', null=True, blank=True)

    amazon_url = models.CharField('アマゾンURL', max_length=1000, null=True, blank=True)
    amazon_url_text = models.CharField('アマゾンURL_text', max_length=1000, null=True, blank=True)
    kindle_url = models.CharField('kindleURL', max_length=1000, null=True, blank=True)
    rakuten_url = models.CharField('楽天URL', max_length=1000, null=True, blank=True)
    rakuten_kobo_url = models.CharField('楽天KOBOURL', max_length=1000, null=True, blank=True)

    book_img_url = models.TextField('商品画像', null=True, blank=True)

    emb_twitter = models.CharField('twitter埋め込み',max_length=10000, null=True, blank=True)
    emb_instagram = models.CharField('instagram埋め込み',max_length=10000, null=True, blank=True)

    def to_dict(i, idex_list, self):
        dict_r = {}
        for index in idex_list:
            dict_ = {}
            # query_ = 'obj_.values_list("{}")[0]'.format(index)
            query_ = 'Book.objects.filter(fin=1).values_list("{}")[{}][0]'.format(index, i)
            if index == "category_info":
                query_ = 'Category.objects.get(id=Book.objects.filter(fin=1).values_list("{}")[{}][0]).get_category_display()'.format(index, i)
            elif index == "author_info":
                query_ = 'Author.objects.get(id=Book.objects.filter(fin=1).values_list("{}")[{}][0]).author'.format(index, i)
            elif index == "post_day":
                query_ = 'Book.objects.filter(fin=1).values_list("{}")[{}][0].strftime("%Y-%m-%d")'.format(index, i)
            exec("{} = {}".format(index, query_), globals(), dict_)
            dict_r = dict_r | dict_
        return dict_r

    def __str__(self):
        return self.title



class Author(models.Model):
    GENDER_CHOICES = (('Mon', '男性'),('Womon', '女性'))
    WORD_CHOICES = (('Aa', 'あ行'),('Ka', 'か行'),('Sa', 'さ行'),('Ta', 'た行'),('Na', 'な行'),('Ha', 'は行'),('Ma', 'ま行'),('Ya', 'や行'),('Ra', 'ら行'),('Wa', 'わ行'))

    author = models.CharField('著者', max_length=100, default=None) # 追加していく-----------
    author_eng = models.CharField('著者eng', max_length=100) # 追加していく-----------
    word_oder = models.CharField('五十音', choices=WORD_CHOICES, max_length=10)
    age = models.DateField('生年月日')
    sex = models.CharField('性別', choices=(('', '未選択'),)+GENDER_CHOICES, max_length=10, blank=True)
    contents = models.TextField("コンテンツ")
    contents_lite = models.TextField("コンテンツ", blank=True, null=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.author
    
class Category(models.Model):
    CATEGORY_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'), ('bungaku', '文学'))
    CATEGORYENG_CHOICES = (('action_eng', 'action'), ('adventure_eng', 'adventure'), ('youth_eng', 'youth'), ('love_eng', 'love'), ('sf_eng', 'sf'), ('history_eng', 'history'), ('mystery_eng', 'mystery'), ('comedy_eng', 'comedy'), ('horror_eng', 'horror'), (('bungaku_eng', 'bungaku')))
    # CATEGORYENG_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'))
    COLOR_CHOICES = (('red', 'red'), ('orange','orange'),('blue', 'blue'), ('pink', 'pink'),('info','info'), ('green', 'green'), ('purple', 'purple'), ('warning','warning'),('dark', 'dark'), ('blue-grey', 'blue-grey'))

    category = models.CharField("カテゴリー", choices=CATEGORY_CHOICES, max_length=20, default=None, null=True, blank=True) # 追加していく-----------
    category_eng = models.CharField("カテゴリーeng", choices=CATEGORYENG_CHOICES ,max_length=20, null=True, blank=True) # 追加していく-----------
    color = models.CharField("色", choices=COLOR_CHOICES, max_length=20)
    color_hex = models.CharField("色_hex値", max_length=20,  blank=True)

    contents = models.TextField("コンテンツ", blank=True)
    contents_keyword = models.TextField("キーワード", blank=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.category

class Publisher(models.Model):
    publisher = models.CharField('出版社', max_length=50)
    publisher_eng = models.CharField('出版社_eng', max_length=50, blank=True, null=True)
    contents = models.TextField("コンテンツ")
    incorporated = models.DateField('設立日')

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.publisher

class Publisher_label(models.Model):
    publisher = models.ForeignKey("Publisher", verbose_name=("出版者"), on_delete=models.CASCADE, null=True, blank=True)
    label = models.CharField("ラベル", max_length=20, default=None) # 追加していく-----------
    label_eng = models.CharField("ラベルeng", max_length=20, default=None) # 追加していく-----------
    def __str__(self):
        return self.label

class Series(models.Model):
    series = models.CharField("シリーズ", max_length=100)
    contents = models.TextField("コンテンツ")

    author = models.ForeignKey("Author", verbose_name=("著者"), on_delete=models.CASCADE)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.series


class Inquiry(models.Model):
    id = models.AutoField("id", primary_key = True)
    name = models.CharField("ニックネーム", max_length=50)
    mail_add = models.EmailField("メールアドレス", max_length=254)
    inquiry = models.TextField("問い合わせ内容", max_length=2047)

class Other(models.Model):
    title = models.CharField('タイトル', max_length=100, null=True, blank=True)
    post_day = models.DateField('投稿日', null=True, blank=True) # [投稿日, y m d]
    update_day = models.DateField('更新日', null=True, blank=True) # [投稿日, y m d]
    
    image = models.ImageField(upload_to='media')
    contents = models.TextField("コンテンツ", null=True, blank=True)
    contents_synopsis =  models.TextField("あらすじ", null=True, blank=True)

    fin = models.BooleanField('完読', null=True, blank=True)

    def __str__(self):
        return self.title





class Templates(models.Model):
    breadcrumb = models.TextField("目次")

    










class Departments(models.Model):
    DepartmentId = models.AutoField(primary_key=True)
    DepartmentName = models.CharField(max_length=500)

class Employees(models.Model):
    EmployeeId = models.AutoField(primary_key=True)
    EmployeeName = models.CharField(max_length=500)
    Department = models.CharField(max_length=500)
    DateOfJoining = models.DateField()
    PhotoFileName = models.CharField(max_length=500)







""" 予定 ----------------------------
作品タイトル
出版日
・y
・m
・d
ページ数
画像
感想（コンテンツ）


アマゾンリンク

■集英社
■カテゴリー
　※複数あり
■著者
・男/女
・生まれ年
・
----------------------------"""

myblog/book/templates/book/components/block/bottom_navigation_.html
<template>
    <v-bottom-navigation
      :value="value"
      {% comment %} color="primary" {% endcomment %}
      class="my-bg-color-glay rounded-lg my-5"
      {% comment %} active-class="my-text-color-light-glay" {% endcomment %}
      color="#f5f8f5"
      grow
>      

      {%if item_prev != "" %}
    
      <v-btn style="display: inline; text-align: center;" href="{% url url_ data_info=item_prev.post_day %}" class="px-2 mx-auto">
        <v-text class="my-text-color-light-glay" style="overflow: hidden; width: 100%; text-overflow: ellipsis;">({{ item_prev.title }})</v-text>
        <span class="my-text-color-light-glay">前の記事</span>
        <v-icon class="my-text-color-light-glay">mdi-arrow-left-thick</v-icon>
      </v-btn>
      {% endif %}

      <v-btn class="px-2 mx-auto" href="{% url url_2 %}">
        <span class="my-text-color-light-glay">{{ sub_text }}</a></span>

        <v-icon class="my-text-color-light-glay">{{ mdi_bottom_navigation }}</v-icon>
      </v-btn>
  
      {%if item_next != "" %}

      <v-btn style="display: inline; text-align: center;" href="{% url url_ data_info=item_next.post_day %}" class="px-2 mx-auto">
          <v-text class="my-text-color-light-glay" style="overflow: hidden; width: 100%; text-overflow: ellipsis;">({{ item_next.title }})</v-text>
          <span class="my-text-color-light-glay my-w-100">次の記事</span>  
          <v-icon class="my-text-color-light-glay my-w-100">mdi-arrow-right-thick</v-icon>
      </v-btn>

      
      {% endif %}


    </v-bottom-navigation>
  </template>

myblog/book/templates/book/components/block/bottom_navigation_judge.html
{% load static %}






  {% if url_sub == "ホーム" %}
    {% with items=book_other_list %}
      {% include 'block/bottom_navigation_.html' with items=book_other_list item_info="" %}
    {% endwith%}

  {% elif url_sub == "書籍一覧" %}
    {% with items=book_list %}
      {% include 'block/bottom_navigation_.html' with item_prev=book_info_prev item_next=book_info_next sub_text="書籍一覧" mdi_bottom_navigation="mdi-bookshelf" url_='book:book_info' url_2='book:book' %}
    {% endwith%}

    {% elif url_sub == "その他 記事" %}
      {% with items=other_list %}
        {% include 'block/bottom_navigation_.html' with item_prev=other_info_prev item_next=other_info_next sub_text="その他 記事一覧" mdi_bottom_navigation="mdi-dots-horizontal-circle-outline" url_='book:others_info' url_2='book:others' %}
      {% endwith%}
  {% endif %}

myblog/book/templates/book/components/block/img_amazon_text.html
{% load static %}
<div class="my-h-100 my-w-100">
  <a d-flex class="my-h-100 my-w-100">
  </a>
<div class="d-flex my-h-100 my-w-100">
    <div class="ml-auto mt-auto mb-0 my-w-50 mr-0 ml-auto" style="">
        <a href="{{amazon_url_text}}" class="my-w-100" target="_blank" style="z-index: 100; position: relative;" >
          <img
            class="my-w-100 my-h-100" style="left: auto; right: auto; background: rgba(255,255,255,.3);z-index: 100; max-height: 100px;"  src="{% static "static/amazon-ar21.svg" %}">
          </img>
        </a>
    </div>
</div>
</div>

myblog/book/templates/book/components/block/img_small copy.html
% load static %}

{% load get_img_src %}
{% load get_tag_el %}

<v-img

{% if img_url|length < 1000 %}
src="{{ img_url | safe }}"
{% else %}
src="/media/{{ img_url | safe }}"
{% endif %}


{% if book_ is not None %}
{% comment %} href="{% if amazon_url_text is not "" %}{% url 'book:book_info' book_.post_day %}{%else%}{% url 'book:others_info' book_.post_day %}{%endif%}" {% endcomment %}
{% endif %}




lazy-src="{% static "static/book-ic_picture_wings.svg" %}"
{% comment %} aspect-ratio="1" {% endcomment %}
class="lighten-2 ma-3 mt-3 mt-sm-10 mt-md-11 mt-lg-12 mb-md-5 mb-lg-3 ml-4 ml-sm-5 ml-md-7 my-border mt-5 elevation-2"
transition="scale-transition"
>

<a href="{% if amazon_url_text != "" %}{% url 'book:book_info' item.post_day %}{%else%}{% url 'book:others_info' item.post_day %}{%endif%}" class="my-w-100 my-h-100" style="position: absolute">
  <div>
  
  </div>
  </a>

<template v-slot:placeholder>
<v-row
  class="fill-height ma-0"
  align="center"
  justify="center"
>
  <v-progress-circular
    indeterminate
    color="grey lighten-5"
  ></v-progress-circular>
</v-row>
</template>



{%if amazon_url_text != "" %}

{% include 'block/img_amazon_text.html' with amazon_url_text=amazon_url_text %}


{% comment %} <a class="mr-0 ml-auto mt-auto mb-0">
  {{amazon_url_text}}
</a> {% endcomment %}
{% endif %}



</v-img>

myblog/book/templates/book/components/block/toolbar.html
{% load static %}


{% comment %} <div style="height:66px"></div> {% endcomment %}

{% comment %} <div id="header_menu" style="position: fixed; z-index:100;"> {% endcomment %}
  <div id="header_menu" class="">
    <v-toolbar
    class="my-w-100 my-bg-color-glay"
    color="#f5f8f5"
    flat
    height="70px"
    {% comment %} width="100%" {% endcomment %}
    tile
    elevation="2"
    style="background: rgb(245, 248, 245, 0.9);"
    {% comment %} absolute {% endcomment %}
    class="position: absolute; top:150px; left:100px"
    {% comment %} absolute {% endcomment %}
    {% comment %} prominent {% endcomment %}
    {% comment %} src="{% static "static/media.jpg" %}" {% endcomment %}
    >
      <v-toolbar-title onclick="location.href='{% url "book:top" %}'" style="cursor:pointer" id="my-letter-spacing-title" class="text-h5_5 text-md-h5 my-text-color-title my-text-color-light-glay my-font-weight-title">BOOK I.C.</v-toolbar-title>

      <v-spacer></v-spacer>

      <v-btn icon fab dark color="#55acee" href="https://twitter.com/BOOK_IC">
        <v-icon size="32" >mdi-twitter</v-icon>
      </v-btn>
      <v-btn icon fab dark class="me-5" href="https://www.instagram.com/BOOK_I.C/">
        {% comment %} <v-icon size="32" >mdi-instagram</v-icon> {% endcomment %}
        <img height="32px" width="32px"
          src="{% static "static/instagram.svg" %}">
        </img>
      </v-btn>


      <v-app-bar-nav-icon @click.stop="drawer = !drawer" class="my-text-color-light-glay">
                <v-icon size="32">mdi-format-list-bulleted</v-icon>

      </v-app-bar-nav-icon>

    </v-toolbar>


    
  </div>

  <v-navigation-drawer
  v-model="drawer"
  absolute
  left
  temporary
  style="border: solid #455045; height: 100vh;"
>
  <v-list
    nav
    dense
    class=""
  >
    <v-list-item-group
      {% comment %} v-model="group" {% endcomment %}
      class=""
      {% comment %} active-class="deep-purple--text text--accent-4" {% endcomment %}
    >

      <v-list-item class="mt-3" href="{% url 'book:top' %}">
        <v-list-item-content>
          <v-list-item-title id="my-letter-spacing-3" class="mb-3 my-font-weight-title text-h6 text-center my-text-color-title py-2">
            BOOK I.C.
          </v-list-item-title>
          <v-list-item-subtitle class="text-center my-text-color-glay">
            ～本の感想を創造するブログ～
          </v-list-item-subtitle>
        </v-list-item-content>
      </v-list-item>
      
      <v-divider class="my-2"></v-divider>
      

      


      <v-list-item class="mb-1 my-text-color" href="{% url 'book:top' %}">
        <v-list-item-icon>
          <v-icon>mdi-home</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>ホーム</v-list-item-title>
        </v-list-item-content>
      </v-list-item>



      <v-list-item class="mb-1 my-text-color" href="{% url 'book:book-ic' %}">
        <v-list-item-icon>
          <v-icon>mdi-office-building-marker-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>BOOK I.C. について</v-list-item-title>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="my-text-color" href="{% url 'book:profile' %}">
        <v-list-item-icon>
          <v-icon>mdi-account-circle-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>プロフィール</v-list-item-title>
        </v-list-item-content>
      </v-list-item>

      



      <v-divider class="my-2"></v-divider>
        

      <v-list-item class="mb-1 my-text-color" href="{% url 'book:book' %}">
        <v-list-item-icon>
          <v-icon>mdi-bookshelf</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>書籍一覧</v-list-item-title>
        </v-list-item-content>
      </v-list-item>
      
      <v-list-item class="mb-1 my-text-color" href="{% url 'book:others' %}">
        <v-list-item-icon>
          <v-icon>mdi-dots-horizontal-circle-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>その他 記事</v-list-item-title>
        </v-list-item-content>
      </v-list-item>


      
  

      
      <v-divider class="my-2"></v-divider>


      <v-list-item class="mb-1 my-text-color" href="{% url 'book:privacy_policy' %}">
        <v-list-item-icon>
          <v-icon>mdi-shield-lock-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>プライバシーポリシー</v-list-item-title>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="mb-1 my-text-color" href="{% url 'book:contact' %}">
        <v-list-item-icon>
          <v-icon>mdi-email-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>問い合わせ</v-list-item-title>
        </v-list-item-content>
      </v-list-item>

      <v-list-item class="mb-1 my-text-color" href="{% url 'book:sitemap_book-ic' %}">
        <v-list-item-icon>
          <v-icon>mdi-sitemap-outline</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>サイトマップ</v-list-item-title>
        </v-list-item-content>
      </v-list-item>      
      <v-divider class="my-2"></v-divider>
      

      {% comment %} 

      <v-btn icon fab color="#55acee" href="https://twitter.com/BOOK_IC">
        <v-icon size="28" >mdi-twitter</v-icon>
      </v-btn>
      <v-btn icon fab class="my-text-color me-5" href="https://www.instagram.com/BOOK_I.C/">
        <v-icon size="28" >mdi-instagram</v-icon>
      </v-btn>

 {% endcomment %}

      <v-btn icon fab dark color="#55acee" href="https://twitter.com/BOOK_IC">
        <v-icon size="28" >mdi-twitter</v-icon>
      </v-btn>
      <v-btn icon fab dark class="me-5" href="https://www.instagram.com/BOOK_I.C/">
        {% comment %} <v-icon size="32" >mdi-instagram</v-icon> {% endcomment %}
        <img height="28px" width="28px"
          src="{% static "static/instagram.svg" %}">
        </img>
      </v-btn>



      
{% comment %} 

      <v-treeview
        v-model="tree"
        :open="initiallyOpen"
        :items="items"
        activatable
        item-key="name"
        open-on-click
      >
      <template v-slot:prepend="{ item, open }">
        <v-icon v-if="!item.file">
          [[ open ? 'mdi-folder-open' : 'mdi-folder' ]]
        </v-icon>
        <v-icon v-else>
          [[ files[item.file] ]]
        </v-icon>
      </template>
    </v-treeview> {% endcomment %}





      {% comment %} <v-divider></v-divider> {% endcomment %}

      {% comment %} <v-list-item>
        <v-list-item-title>Buzz</v-list-item-title>
      </v-list-item> {% endcomment %}
    </v-list-item-group>
  </v-list>
</v-navigation-drawer>
  