myblog/book/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
# from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import resolve_url
from django.urls import path, include
from .models import Book, Other
import datetime

from django.views.decorators.cache import cache_page



app_name='book'

class PostSitemap_Book(Sitemap):
    changefreq = "never"
    priority = 0.6

    def items(self):
        return Book.objects.filter(fin=True)

    def location(self, obj):
        data_info=(obj.post_day).strftime("%Y-%m-%d")
        # data_info= obj.post_day
        return resolve_url('book:book_info', data_info=data_info)+"1/"

    def lastmod(self, obj):
        return obj.post_day

class PostSitemap_Other(Sitemap):
    changefreq = "never"
    priority = 0.4

    def items(self):
        return Other.objects.all()

    def location(self, obj):
        data_info=(obj.post_day).strftime("%Y-%m-%d")
        # data_info= obj.post_day
        return resolve_url('book:others_info', data_info=data_info)

    def lastmod(self, obj):
        return obj.post_day

class StaticSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        name_list = ['profile', 'book-ic', 'others', 'privacy_policy', 'contact', 'book', 'top', 'sitemap_book-ic', 'ads']
        items = []
        for name_ in name_list:
            items.append("book:{}".format(name_))          
        return items

    def location(self, obj):
        return resolve_url(obj)


sitemaps = {
    'posts_book': PostSitemap_Book,
    'posts_other':PostSitemap_Other,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.TopView.as_view(), name="top"),
    path('quasar/', views.TopquasarView.as_view(), name="top_quasar"),

    path('categorys/', views.CategoryView.as_view(), name='category'),# 本のカテゴリー
    path('categorys/<slug:data_info>/', views.CategoryView.as_view(), name='category_infprofile', ),

    path('authors/', views.AuthorView.as_view(), name='author'), # 著者について全般
    path('authors/<data_info>/', views.AuthorView.as_view(), name='author_info'),

    path('publishers/', views.PublisherView.as_view(), name='publisher'), # 出版社情報
    path('publishers/<slug:data_info>/', views.PublisherView.as_view(), name='publisher_info'),

    path('series/', views.SeriesView.as_view(), name='series'), # シリーズもの本
    path('series/<slug:data_info>/', views.SeriesView.as_view(), name='series_info'), 

    path('books/', views.BookView.as_view(), name='book'), # 主に本の検索と
    path('books/<slug:data_info>/', views.BookrView.as_view(), name='book_info'), 
    path('books/<slug:data_info>/<int:data_info_page>/', views.BookView.as_view(), name='book_info_content'), 

    path('search', views.SearchView.as_view(), name='search' ), # 本の検索全般

    path('articles/', views.ArticlesView.as_view(), name='article'), # トピックスに近いもの

    # path('otherss/', views.OtherView.as_view(),  name='other'),
    path('others/shedule', views.Schedule.as_view(),  name='schedule'),

    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('book-ic/', views.Book_icView.as_view(), name="book-ic"),

    path('others/', views.OthersView.as_view(), name="others"),
    path('others/<slug:data_info>/', views.OthersView.as_view(), name="others_info"),


    path('privacypolicy', views.Privacy_policyView.as_view(), name="privacy_policy"),
    path('contact', views.ContactView.as_view(), name="contact"),
    

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},  name='sitemap'),
    path('sitemap/', views.SitemapView.as_view(),  name='sitemap_book-ic'),

    path('ads.txt/', views.ads, name='ads'),

    path('test/', views.test_,  name='test_'),
    
    # path('base', views.TestView.as_view(), name="base"),


    ]

if settings.DEBUG == True:
    urlpatterns.append(path('sns/books/<slug:data_info>/', views.Picture_snsView.as_view(),  name='picture_sns'))

# 


""" 予定-----------------------------
top
    -Recently （最近の投稿）
    -auther（著者）一覧のみ[（あいうえお順）/（男・女）/（年齢）]
        -著者の情報　＋　Book[カテゴリー/出版日]
    -Publisher（出版社）一覧のみ
        -出版社の情報　＋　Author[（あいうえお順）/（男・女）/（年齢）]
    -category（カテゴリー）
    -読む予定の本一覧a
    -外部リンク[アリクイちゃんねる/技術コンテンツ/ヨウヘイ]

search
    -カテゴリー
    -出版社
    -著者
    -日付

-----------------------------"""

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



# if settings.DEBUG != True:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('book.urls')),
#     ]
# else:
urlpatterns = [
    path('', include('book.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG == True:
    urlpatterns.append(path('admin/', admin.site.urls))

 



# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


# from django.views.static import serve  #追加

# url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  #追加

myblog/book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.aggregates import Count
from django.db.models.enums import Choices
from django.db.models.fields import SmallIntegerField, TimeField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.reverse_related import ManyToOneRel
from django.core.validators import MinLengthValidator, RegexValidator
import datetime


# いらないｰｰｰｰｰｰｰｰ
# sex_ = (
#     ("man", '男性'),
#     ("woman", '女性')
# )
# ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ

# Create your models here.


class Book(models.Model):
    isbn13 = models.CharField(max_length=14,
                                validators=[MinLengthValidator(14, '文字数が一致していません。例）978-4167174033'),
                                            RegexValidator(r'[0-9]{3}[-][0-9]{10}', '形式に当てはまっていません。例）978-4167174033')], null=True, blank=True)

    title = models.CharField('タイトル', max_length=100, null=True, blank=True)
    pages = models.SmallIntegerField('ページ数', null=True, blank=True)
    issue = models.DateField('発行日', null=True, blank=True) # [発行日, y m d]

    post_day = models.DateField('投稿日', null=True, blank=True) # [投稿日, y m d]
    update_day = models.DateField('更新日', null=True, blank=True) # [投稿日, y m d]


    YOUTH_CHOICES = (('Y', 'Youth'),('O', 'Old'))
    youth_choices = models.CharField('青春/白秋', choices=YOUTH_CHOICES, max_length=10)

    series_info = models.ForeignKey("Series", verbose_name=("シリーズ情報"), on_delete=models.CASCADE, null=True, blank=True)
    author_info = models.ForeignKey("Author", verbose_name=("著者情報"), on_delete=models.CASCADE, null=True, blank=True)
    # category_info = models.ManyToManyField("Category", verbose_name=("カテゴリー情報"), blank=True, related_name="category_info")
    category_info = models.ForeignKey("Category", verbose_name=("カテゴリー情報"), blank=True,null=True,on_delete=models.CASCADE)

    publisher_info = models.ForeignKey("Publisher", verbose_name=("出版社情報"), on_delete=models.CASCADE, null=True, blank=True)
    publisher_label_info = models.ForeignKey("Publisher_label", verbose_name=("レーベル"), on_delete=models.CASCADE, null=True, blank=True)

    contents = models.TextField("コンテンツ", null=True, blank=True)
    contents_synopsis =  models.TextField("あらすじ", null=True, blank=True)

    fin = models.BooleanField('完読', null=True, blank=True)

    amazon_url = models.CharField('アマゾンURL', max_length=1000, null=True, blank=True)
    amazon_url_text = models.CharField('アマゾンURL_text', max_length=1000, null=True, blank=True)
    kindle_url = models.CharField('kindleURL', max_length=1000, null=True, blank=True)
    rakuten_url = models.CharField('楽天URL', max_length=1000, null=True, blank=True)
    rakuten_kobo_url = models.CharField('楽天KOBOURL', max_length=1000, null=True, blank=True)

    book_img_url = models.TextField('商品画像', null=True, blank=True)

    emb_twitter = models.CharField('twitter埋め込み',max_length=10000, null=True, blank=True)
    emb_instagram = models.CharField('instagram埋め込み',max_length=10000, null=True, blank=True)

    def to_dict(i, idex_list, self):
        dict_r = {}
        for index in idex_list:
            dict_ = {}
            # query_ = 'obj_.values_list("{}")[0]'.format(index)
            query_ = 'Book.objects.filter(fin=1).values_list("{}")[{}][0]'.format(index, i)
            if index == "category_info":
                query_ = 'Category.objects.get(id=Book.objects.filter(fin=1).values_list("{}")[{}][0]).get_category_display()'.format(index, i)
            elif index == "author_info":
                query_ = 'Author.objects.get(id=Book.objects.filter(fin=1).values_list("{}")[{}][0]).author'.format(index, i)
            elif index == "post_day":
                query_ = 'Book.objects.filter(fin=1).values_list("{}")[{}][0].strftime("%Y-%m-%d")'.format(index, i)
            exec("{} = {}".format(index, query_), globals(), dict_)
            dict_r = dict_r | dict_
        return dict_r

    def __str__(self):
        return self.title



class Author(models.Model):
    GENDER_CHOICES = (('Mon', '男性'),('Womon', '女性'))
    WORD_CHOICES = (('Aa', 'あ行'),('Ka', 'か行'),('Sa', 'さ行'),('Ta', 'た行'),('Na', 'な行'),('Ha', 'は行'),('Ma', 'ま行'),('Ya', 'や行'),('Ra', 'ら行'),('Wa', 'わ行'))

    author = models.CharField('著者', max_length=100, default=None) # 追加していく-----------
    author_eng = models.CharField('著者eng', max_length=100) # 追加していく-----------
    word_oder = models.CharField('五十音', choices=WORD_CHOICES, max_length=10)
    age = models.DateField('生年月日')
    sex = models.CharField('性別', choices=(('', '未選択'),)+GENDER_CHOICES, max_length=10, blank=True)
    contents = models.TextField("コンテンツ")
    contents_lite = models.TextField("コンテンツ", blank=True, null=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.author
    
class Category(models.Model):
    CATEGORY_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'), ('bungaku', '文学'))
    CATEGORYENG_CHOICES = (('action_eng', 'action'), ('adventure_eng', 'adventure'), ('youth_eng', 'youth'), ('love_eng', 'love'), ('sf_eng', 'sf'), ('history_eng', 'history'), ('mystery_eng', 'mystery'), ('comedy_eng', 'comedy'), ('horror_eng', 'horror'), (('bungaku_eng', 'bungaku')))
    # CATEGORYENG_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'))
    COLOR_CHOICES = (('red', 'red'), ('orange','orange'),('blue', 'blue'), ('pink', 'pink'),('info','info'), ('green', 'green'), ('purple', 'purple'), ('warning','warning'),('dark', 'dark'), ('blue-grey', 'blue-grey'))

    category = models.CharField("カテゴリー", choices=CATEGORY_CHOICES, max_length=20, default=None, null=True, blank=True) # 追加していく-----------
    category_eng = models.CharField("カテゴリーeng", choices=CATEGORYENG_CHOICES ,max_length=20, null=True, blank=True) # 追加していく-----------
    color = models.CharField("色", choices=COLOR_CHOICES, max_length=20)
    color_hex = models.CharField("色_hex値", max_length=20,  blank=True)

    contents = models.TextField("コンテンツ", blank=True)
    contents_keyword = models.TextField("キーワード", blank=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.category

class Publisher(models.Model):
    publisher = models.CharField('出版社', max_length=50)
    publisher_eng = models.CharField('出版社_eng', max_length=50, blank=True, null=True)
    contents = models.TextField("コンテンツ")
    incorporated = models.DateField('設立日')

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.publisher

class Publisher_label(models.Model):
    publisher = models.ForeignKey("Publisher", verbose_name=("出版者"), on_delete=models.CASCADE, null=True, blank=True)
    label = models.CharField("ラベル", max_length=20, default=None) # 追加していく-----------
    label_eng = models.CharField("ラベルeng", max_length=20, default=None) # 追加していく-----------
    def __str__(self):
        return self.label

class Series(models.Model):
    series = models.CharField("シリーズ", max_length=100)
    contents = models.TextField("コンテンツ")

    author = models.ForeignKey("Author", verbose_name=("著者"), on_delete=models.CASCADE)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.series


class Inquiry(models.Model):
    id = models.AutoField("id", primary_key = True)
    name = models.CharField("ニックネーム", max_length=50)
    mail_add = models.EmailField("メールアドレス", max_length=254)
    inquiry = models.TextField("問い合わせ内容", max_length=2047)

class Other(models.Model):
    title = models.CharField('タイトル', max_length=100, null=True, blank=True)
    post_day = models.DateField('投稿日', null=True, blank=True) # [投稿日, y m d]
    update_day = models.DateField('更新日', null=True, blank=True) # [投稿日, y m d]
    
    image = models.ImageField(upload_to='media')
    contents = models.TextField("コンテンツ", null=True, blank=True)
    contents_synopsis =  models.TextField("あらすじ", null=True, blank=True)

    fin = models.BooleanField('完読', null=True, blank=True)

    def __str__(self):
        return self.title





class Templates(models.Model):
    breadcrumb = models.TextField("目次")

    










class Departments(models.Model):
    DepartmentId = models.AutoField(primary_key=True)
    DepartmentName = models.CharField(max_length=500)

class Employees(models.Model):
    EmployeeId = models.AutoField(primary_key=True)
    EmployeeName = models.CharField(max_length=500)
    Department = models.CharField(max_length=500)
    DateOfJoining = models.DateField()
    PhotoFileName = models.CharField(max_length=500)







""" 予定 ----------------------------
作品タイトル
出版日
・y
・m
・d
ページ数
画像
感想（コンテンツ）


アマゾンリンク

■集英社
■カテゴリー
　※複数あり
■著者
・男/女
・生まれ年
・
----------------------------"""

myblog/book/templates/book/_block_static.html
{% comment %} {% load static %} {% endcomment %}




<!DOCTYPE html>
<html>


<!-- head -->
{% include 'block/head.html' %}
<style>
  [v-cloak] {
    display: none;
  }
</style>


<body>
  {% if  DEBUG == False %}
    {% include 'block/tag_google_body.html' %}
  {% endif %}

  <div id="app" v-cloak>
    <v-app id="inspire" class="my-bg-color"  v-cloak>


        <!-- toolbar -->
        {% include 'block/toolbar.html' %}


        {% comment %} {% load static %} {% endcomment %}



      

        <v-container id="my_container" class="mx-auto"> 

          {% comment %} {% load cache %} {% endcomment %}
          {% comment %} {% cache 600 content %} {% endcomment %}
        <!-- content -->
        {% block contents %}
        {% endblock %}
          {% comment %} {% endcache %} {% endcomment %}
        </v-container>
        

        <!-- google広告_multiplex -->
        {% comment %} {% if request.path != %} {% endcomment %}
          {% if breadcrumb.2.title_info == None and breadcrumb.1.title_info is not "書籍一覧" %}
        <v-row no-gutters>
          <v-col
            cols="12"
            sm="12"
            lg="11"
            class="py-10 px-2 mx-auto my-auto"
            align-self="center"
          >
          {% include 'google/adsense_multiplex.html' %}
          </v-col>
      </v-row>
      {% endif %}

        <v-divider class="py-10 my-10" style="border-color: #f5f8f5; height: 30vh;"></v-divider>

        <!-- footer -->
        {% include 'block/footer.html' %}

    </v-app>    
  </div>
</body>




<!-- style -->
{% include 'scripts_css_comp/style.html' %}

<!-- components-->
{% include 'scripts_css_comp/components.html' %}


<!-- script -->
{% include 'scripts_css_comp/script.html' %}

{% if  DEBUG == False %}
<script>
  [].forEach.call(document.querySelectorAll('.adsbygoogle'), function(){
      (adsbygoogle = window.adsbygoogle || []).push({});
  });
</script>
{% endif %}      




<style scoped>
  #app /deep/ .v-application {
    font-family: 'Sawarabi Gothic', 'Noto Sans JP','Noto Sans',sans-serif !important;
  }
  #app /deep/ .text-md-h6 {
    font-family: 'Sawarabi Gothic', 'Noto Sans JP','Noto Sans',sans-serif !important;
  }  
</style>
</html>

myblog/book/templates/book/card.html
 <v-container id="my_container" class="my-16 mx-auto">
    <v-row
      no-gutters
    >
    <v-col
        cols="12"
        align-self="center"
        class="mx-auto"
      >
    <p class="text-h2 my-text-color-title text-h5 text-md-h4" style="letter-spacing:3px;">
      <v-icon size="40" >mdi-book-open-page-variant</v-icon>
  
      最近の投稿</p>
  </v-col>
  
  {% for book_ in book_list %}
    <v-col
        cols="10"
        md="6"
        lg="4"
        align-self="center"
        class="px-3 mb-14 mx-auto mt-5 mb-auto"
      >
    
  
      <v-card
        class="mx-auto my-bg-color-glay"
        elevation="15"
        style=""
      >
        <v-img min-width="100"
        >{{ book_.amazon_url | safe }}</v-img>
    
        <div style="background-color:white;">
        <v-card-text class="pb-0 my-text-color" style="border-top: solid 0.2em;">
          {{ book_.post_day | safe }}
        </v-card-text>
  
  
        <v-card-title class="pb-0 pt-1">
          {{ book_.title | safe }}
        </v-card-title>
  
        <v-card-text class="ms-2">
          <v-icon color="#9A9" size="14">mdi-eye</v-icon>
          <a class="ms-1 me-3 text-subtitle-2 text-md-subtitle-1 my-text-color-glay">XXX,XXX,XXX</a>
        </v-card-text>
  
        
        <v-card-actions>
          <v-btn color="{{book_.category_info.color_hex}}" elevation="1" outlined rounded small>
            <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
              <input type="submit" href="{% url "book:book" %}" value="{{book_.category_info.get_category_display}}">
            </form>
          </v-btn>
  
  
          <v-btn color="#455045" elevation="1" outlined rounded small>
            <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
              <input type="submit" href="{% url "book:book" %}" value="{{ book_.author_info }}">
            </form>
          </v-btn>
          <v-btn color="#455045" elevation="1" outlined rounded small>
            <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
              <input type="submit" href="{% url "book:book" %}" value="{{ book_.publisher_info}}">
            </form>
          </v-btn>
        </v-card-actions>
        <v-card-text>
          {{ book_.contents_synopsis | safe }}
        </v-card-text>
  
        <v-spacer></v-spacer>
    
  
  
        <v-card-actions>
          <v-btn color="#1aa179" text class="flex-child-right" href ="{% url 'book:book_info' book_.post_day %}">
          この記事を読む
        </v-btn>
        </v-card-actions>
  
  
        {% comment %} 
    
        <v-expand-transition>
          <div v-show="show">
            <v-divider></v-divider>
    
  
          </div>
        </v-expand-transition> {% endcomment %}
      </div>
      </v-card>
    </v-col>
    {% endfor %}
  
  </v-row>
  </v-container>
  
  

myblog/book/templates/book/err.html
何かミスってる

myblog/book/templates/book/footer.html
<v-footer
padless
dark
class="my-bg-color-glay"
>
<v-card
  flat
  tile
  class="lighten-1 white--text text-center my-bg-color-glay my-text-color-light-glay"
  style="width: 100%"
>




<div class="px-6 pt-10 my-text-color-light-glay">
  <v-card-title class="pa-0 pb-1">
    カテゴリー
  </v-card-title>
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in category %}
    <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
      <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
        <input type="submit" href="{% url "book:book" %}" value="{{item.get_category_display}}">
      </form>
    </v-btn>
    {% endfor %}
  </v-card-text>
</div>




<div class="px-6 pt-4 ">
  <v-card-title class="pa-0 pb-1">
    著者
  </v-card-title>
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in author_Aa %}
    {% for item2 in item %}
      {% if forloop.first %}
      <div class="me-auto mb-2 mb-lg-0 text-start mt-1 pr-5" style="display: inline-block;">
        <a class="text-white">{{item2.get_word_oder_display}}</a>
      {% endif %}


        <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
          <form action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="author" value={{ item2.author }}><input type="hidden" name="age_low" value='1900-1-1'><input type="hidden" name="age_high" value={{ date_now|date:"Y-n-j" }}><input type="submit" href="{% url "book:book" %}" value="{{ item2.author }}"></form>
          {% comment %} <form class="d-inline-block fs-5_5" action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="author" value={{ item2.author }}><input type="hidden" name="age_low" value='1900-1-1'><input type="hidden" name="age_high" value={{ date_now|date:"Y-n-j" }}><input type="submit" class="text-decoration-none py-0 px-01 my-1 d-inline-block px-01 py-0 border rounded btn-dark" href="{% url "book:book" %}" value="{{ item2.author }}"></form>         {% endcomment %}
        </v-btn>
        {% if forloop.last %}
        </div>
        {% endif %}
      {% endfor %}
    {% endfor %}
      </v-card-text>
</div>





<div class="px-6 pt-4 ">
  <v-card-title class="pa-0 pb-1">
  出版社
</v-card-title>
<v-card-text class="pl-3 pt-0" style="text-align: left;">
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in publisher %}
    <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
      <form action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="publisher" value={{ item.publisher_eng}}><input type="submit" href="{% url "book:book" %}" value="{{ item.publisher}}"></form>
      {% comment %} <form class="text-decoration-none py-0 px-01 my-1 d-inline-block fs-5_5" action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="publisher" value={{ item.publisher_eng}}><input type="submit" class="text-decoration-none py-0 px-01 my-1 d-inline-block px-01 py-0 border rounded btn-dark" href="{% url "book:book" %}" value="{{ item.publisher}}"></form> {% endcomment %}
    </v-btn>
    {% endfor %}
  </v-card-text>
</div>








  {% comment %} <v-card-text class="white--text pt-8">
    Phasellus feugiat arcu sapien, et iaculis ipsum elementum sit amet. Mauris cursus commodo interdum. Praesent ut risus eget metus luctus accumsan id ultrices nunc. Sed at orci sed massa consectetur dignissim a sit amet dui. Duis commodo vitae velit et faucibus. Morbi vehicula lacinia malesuada. Nulla placerat augue vel ipsum ultrices, cursus iaculis dui sollicitudin. Vestibulum eu ipsum vel diam elementum tempor vel ut orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  </v-card-text> {% endcomment %}

  <v-card-text class="my-text-color-light"  style="text-align:right;">

    <v-btn icon fab xlarge dark class="mx-0 my-text-color-light-glay" href="https://twitter.com/BOOK_IC">
      <v-icon size="24" >mdi-twitter</v-icon>
    </v-btn>
    <v-btn icon fab xlarge dark class="mx-0 my-text-color-light-glay" href="https://www.instagram.com/BOOK_I.C/">
      <v-icon size="24" >mdi-instagram</v-icon>
    </v-btn>
</v-card-text>

  <v-divider></v-divider>

  <v-card-text class="my-text-color-light">
    <strong>Copyright © 2022 「BOOK I.C.」 All Rights Reserved.</strong>
      

  </v-card-text>
</v-card>
</v-footer>